"""Shared atomic compliance checks (overlap groups).

Standards compose from these groups. Same ``group_id`` = overlapping requirement;
multi-standard runs execute each group once and map results.
"""

from __future__ import annotations

from typing import Any, Dict

# Canonical atomic checks keyed by group_id
SHARED_CHECKS: Dict[str, Dict[str, Any]] = {
    "api_trail_30d": {
        "group_id": "api_trail_30d",
        "category": "透明度",
        "requirement": "必须记录过去 30 天内所有 API 调用的时间、端点与费用，并纳入审计轨迹。",
        "check_method": "查询过去 30 天 API 调用；要求至少 1 条且含 timestamp/endpoint/cost_usd/chain_hash。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "has_calls_with_required_fields",
        "how_to_satisfy": "通过审计代理接入流量，确保调用写入 api_calls 并挂接哈希链；至少保留 30 天窗口。",
    },
    "hash_chain": {
        "group_id": "hash_chain",
        "category": "安全",
        "requirement": "审计记录必须挂接防篡改哈希链，且整链可验证完整。",
        "check_method": "对 attestation_chain 执行统一验链。",
        "auto_check": True,
        "query_template": None,
        "pass_rule": "chain_integrity",
        "how_to_satisfy": "勿手工改库；使用本产品代理/模拟写入；在防篡改面板确认「链完整」。",
    },
    "endpoint_recorded": {
        "group_id": "endpoint_recorded",
        "category": "透明度",
        "requirement": "每条 API 调用必须记录完整端点路径。",
        "check_method": "过去 30 天调用 endpoint 非空比例 = 100%。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "all_have_endpoint",
        "how_to_satisfy": "确认代理正确转发 path；拒绝无端点的脏数据写入。",
    },
    "model_recorded": {
        "group_id": "model_recorded",
        "category": "透明度",
        "requirement": "调用记录必须披露所用模型标识。",
        "check_method": "过去 30 天 model 非空比例 ≥ 90%。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "model_coverage_ge_90",
        "how_to_satisfy": "请求体携带 model；计量层从响应解析模型名并落库。",
    },
    "cost_recorded": {
        "group_id": "cost_recorded",
        "category": "计费",
        "requirement": "每条调用必须有可对账的费用字段（cost_usd）。",
        "check_method": "过去 30 天均含 cost_usd。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "all_have_cost",
        "how_to_satisfy": "启用计量模块；核对 usage tokens 与计价表。",
    },
    "failures_audited": {
        "group_id": "failures_audited",
        "category": "安全",
        "requirement": "失败的 API 调用同样必须进入审计轨迹。",
        "check_method": "失败调用具备 chain_hash；无失败则通过。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "status": "failure", "limit": 200},
        "pass_rule": "failures_have_chain_or_none",
        "how_to_satisfy": "代理在 4xx/5xx 时仍写 attestation 记录。",
    },
    "body_hashes": {
        "group_id": "body_hashes",
        "category": "安全",
        "requirement": "请求/响应须有 request_hash 与 response_hash（可不落盘正文）。",
        "check_method": "过去 30 天均含非空 body 哈希。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "all_have_body_hashes",
        "how_to_satisfy": "使用本产品代理路径；勿绕过哈希写入。",
    },
    "capability_disclosure": {
        "group_id": "capability_disclosure",
        "category": "透明度",
        "requirement": "必须向用户披露模型能力边界与已知限制。",
        "check_method": "人工审查产品文档/用户协议。",
        "auto_check": False,
        "manual_guidance": "检查公开文档是否列出能力、禁止用途与失效场景；保留版本与日期。",
        "how_to_satisfy": "发布模型卡/能力说明页，并归档 PDF 哈希到证据库。",
    },
    "training_data": {
        "group_id": "training_data",
        "category": "数据使用",
        "requirement": "必须披露训练数据来源类别（或书面说明不可披露原因）。",
        "check_method": "人工审查训练数据声明。",
        "auto_check": False,
        "manual_guidance": "在模型卡或合规附录定位训练数据来源声明。",
        "how_to_satisfy": "补充训练数据来源章节；无法披露时出具书面理由。",
    },
    "user_data_training": {
        "group_id": "user_data_training",
        "category": "数据使用",
        "requirement": "用户数据是否用于模型训练须有明确可审计政策。",
        "check_method": "人工审查隐私政策训练条款。",
        "auto_check": False,
        "manual_guidance": "核对「用于训练: yes/no」及 opt-out 路径。",
        "how_to_satisfy": "更新隐私政策；提供 opt-out；保留政策版本哈希。",
    },
    "usage_limits": {
        "group_id": "usage_limits",
        "category": "透明度",
        "requirement": "必须披露使用限制（速率、地域、内容类别等）。",
        "check_method": "人工审查使用限制是否可见。",
        "auto_check": False,
        "manual_guidance": "收集速率/地域/内容政策页面 URL 与抓取时间。",
        "how_to_satisfy": "在控制台与文档公开限制；截图归档。",
    },
    # US AI Executive Order oriented
    "safety_assessment": {
        "group_id": "safety_assessment",
        "category": "安全",
        "requirement": "须对高影响 AI 系统开展安全评估并保留可审计证据。",
        "check_method": "人工审查：安全评估报告是否存在、版本与日期是否可追溯。",
        "auto_check": False,
        "manual_guidance": "收集安全评估报告；记录评估范围、日期与签字人。",
        "how_to_satisfy": "完成安全评估并上传报告哈希到证据库；周期复评。",
    },
    "red_team_eval": {
        "group_id": "red_team_eval",
        "category": "安全",
        "requirement": "须开展红队/对抗测试并记录发现与缓解措施。",
        "check_method": "人工审查红队测试计划与结果摘要。",
        "auto_check": False,
        "manual_guidance": "保留红队范围、用例、发现与修复跟踪表。",
        "how_to_satisfy": "执行至少一轮红队；归档报告与修复完成证据。",
    },
    "incident_reporting": {
        "group_id": "incident_reporting",
        "category": "安全",
        "requirement": "须具备 AI 安全事件报告与响应流程。",
        "check_method": "人工审查事件响应 runbook 与最近演练记录。",
        "auto_check": False,
        "manual_guidance": "检查 IR 流程文档与演练日志。",
        "how_to_satisfy": "发布 IR 流程；完成桌面演练并归档纪要。",
    },
    # China GenAI measures
    "cn_filing": {
        "group_id": "cn_filing",
        "category": "合规备案",
        "requirement": "生成式 AI 服务须按管理办法完成备案（或具备备案进度证明）。",
        "check_method": "人工审查备案号/受理回执/进度说明。",
        "auto_check": False,
        "manual_guidance": "核对备案主体、算法名称与公示信息。",
        "how_to_satisfy": "启动备案流程；保存回执与公示链接哈希。",
    },
    "cn_data_security_eval": {
        "group_id": "cn_data_security_eval",
        "category": "数据使用",
        "requirement": "须完成数据安全评估（采集、存储、出境等适用项）。",
        "check_method": "人工审查数据安全评估报告。",
        "auto_check": False,
        "manual_guidance": "确认评估覆盖训练/推理数据流与留存策略。",
        "how_to_satisfy": "委托或自评估；归档评估报告与整改项。",
    },
    "cn_content_moderation": {
        "group_id": "cn_content_moderation",
        "category": "内容安全",
        "requirement": "须具备内容审核机制（输入/输出过滤与人工复核路径）。",
        "check_method": "人工审查内容审核策略与抽检日志。",
        "auto_check": False,
        "manual_guidance": "检查过滤规则、拦截样例与复核工单。",
        "how_to_satisfy": "部署内容审核；保留抽检与拦截证据。",
    },
    "cn_user_realname": {
        "group_id": "cn_user_realname",
        "category": "合规备案",
        "requirement": "面向公众的服务须落实用户真实身份核验（适用时）。",
        "check_method": "人工审查实名/认证接入说明。",
        "auto_check": False,
        "manual_guidance": "确认认证方式与隐私最小化说明。",
        "how_to_satisfy": "接入合规身份核验；记录供应商与协议版本。",
    },
    # ISO/IEC 42001
    "iso_governance": {
        "group_id": "iso_governance",
        "category": "治理",
        "requirement": "须建立 AI 管理系统治理结构（角色、职责、政策）。",
        "check_method": "人工审查 AI 政策与 RACI。",
        "auto_check": False,
        "manual_guidance": "收集政策文件、责任人任命与评审记录。",
        "how_to_satisfy": "发布 AIMS 政策；指定所有者；年度评审。",
    },
    "iso_risk_assessment": {
        "group_id": "iso_risk_assessment",
        "category": "治理",
        "requirement": "须开展并维护 AI 风险评估登记册。",
        "check_method": "人工审查风险登记册与最近更新。",
        "auto_check": False,
        "manual_guidance": "确认风险项、评分、控制与残余风险。",
        "how_to_satisfy": "建立风险登记册；季度更新；链接控制证据。",
    },
    "iso_continual_improvement": {
        "group_id": "iso_continual_improvement",
        "category": "治理",
        "requirement": "须有持续改进机制（度量、评审、纠正措施）。",
        "check_method": "人工审查改进日志与管理评审纪要。",
        "auto_check": False,
        "manual_guidance": "检查 CAPA 与 KPI 回顾。",
        "how_to_satisfy": "定义 KPI；管理评审；关闭纠正措施。",
    },
    "iso_supplier": {
        "group_id": "iso_supplier",
        "category": "治理",
        "requirement": "对第三方模型/云供应商须有尽职调查与合同控制。",
        "check_method": "人工审查供应商清单与 DPA/SLA。",
        "auto_check": False,
        "manual_guidance": "核对供应商评估表与合同条款。",
        "how_to_satisfy": "完成供应商评估；签署 DPA；定期复审。",
    },
    # SOC 2 AI-applicable
    "soc2_security": {
        "group_id": "soc2_security",
        "category": "安全",
        "requirement": "安全控制：访问控制、变更管理与日志可审计（AI 服务适用）。",
        "check_method": "人工审查访问控制与变更日志；机器侧核对哈希链完整。",
        "auto_check": True,
        "query_template": None,
        "pass_rule": "chain_integrity",
        "how_to_satisfy": "强化访问控制；保持审计链完整；保留变更记录。",
    },
    "soc2_availability": {
        "group_id": "soc2_availability",
        "category": "可用性",
        "requirement": "可用性：须定义并监测 AI API 可用性目标。",
        "check_method": "人工审查 SLO/SLA 与可用性仪表盘。",
        "auto_check": False,
        "manual_guidance": "收集 SLO 定义与近 30 天可用性截图。",
        "how_to_satisfy": "定义 SLO；部署监测；保留月度可用性报告。",
    },
    "soc2_processing_integrity": {
        "group_id": "soc2_processing_integrity",
        "category": "处理完整性",
        "requirement": "处理完整性：API 调用处理结果可追溯、可对账。",
        "check_method": "自动：调用具备费用与哈希；人工：对账流程文档。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "has_calls_with_required_fields",
        "how_to_satisfy": "保持计量与哈希链；建立账单对账 runbook。",
    },
    "soc2_confidentiality": {
        "group_id": "soc2_confidentiality",
        "category": "保密性",
        "requirement": "保密性：敏感请求正文不落盘明文，仅保留哈希。",
        "check_method": "自动：存在 request/response hash；人工：确认无正文落盘策略。",
        "auto_check": True,
        "query_template": {"time_range": "30d", "limit": 500},
        "pass_rule": "all_have_body_hashes",
        "how_to_satisfy": "确认产品不存正文；策略文档化。",
    },
    "soc2_privacy": {
        "group_id": "soc2_privacy",
        "category": "隐私",
        "requirement": "隐私：数据处理目的、保留期与数据主体请求流程明确。",
        "check_method": "人工审查隐私政策与 DSAR 流程。",
        "auto_check": False,
        "manual_guidance": "核对保留期、目的限制与 DSAR SLA。",
        "how_to_satisfy": "更新隐私政策；建立 DSAR 工单；归档样例。",
    },
}


def materialize_check(group_id: str, check_id: str) -> Dict[str, Any]:
    base = SHARED_CHECKS[group_id]
    out = dict(base)
    out["check_id"] = check_id
    out["group_id"] = group_id
    return out
